channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=0.23.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - matplotlib=2.2.2
  - numpy=1.16.4
  - numpydoc=0.8.0
  - spacy=2.1.3
  - pip:
    - textstat==0.5.6
    - jupyter
  # - textstat=0.5.6